# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Front

on:
  push:
    branches:
      - main
      # - 'releases/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build-ng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm test --watch false

  build-image-docker:
    needs: build-ng
    runs-on: ubuntu-latest
    steps:

      - name: Build angular
        uses: actions/checkout@v3

      - name: npm install and build
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jmartinarroyo/shop_front:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
